import { OrgApp, Question } from 'interfaces';
import { User, Organization } from '@prisma/client';

/** Dummy user data. */
// eslint-disable-next-line import/prefer-default-export

export const sampleUserData: User[] = [
  {
    id: 101,
    role: 'admin',
    email: 'alice@wonderland.in',
    emailVerified: null,
    image: null,
    hashedPassword: 'beep boop',
    createdAt: new Date('2020-10-26T01:02:07.213Z'),
    updatedAt: new Date('2020-10-26T01:02:07.213Z'),
  },
  {
    id: 102,
    role: 'moderator',
    email: 'bob@builder.com',
    emailVerified: null,
    image: '/buildprint.png',
    hashedPassword: 'i love hammers',
    createdAt: new Date('2020-10-25T01:02:07.213Z'),
    updatedAt: new Date('2020-10-25T01:02:09.213Z'),
  },
  {
    id: 103,
    role: 'moderator',
    email: 'Fred@rick.com',
    emailVerified: null,
    image: null,
    hashedPassword: 'i love code',
    createdAt: new Date('2020-10-24T01:05:07.213Z'),
    updatedAt: new Date('2020-10-24T01:10:07.213Z'),
  },
  {
    id: 104,
    role: 'admin',
    email: 'rick@morty.com',
    emailVerified: new Date('2020-10-23T01:02:07.213Z'),
    image: '/c137.jpeg',
    hashedPassword: 'vat of acid',
    createdAt: new Date('2020-10-23T12:02:07.213Z'),
    updatedAt: new Date('2020-10-23T01:02:07.213Z'),
  },
];

export const sampleOrgData: Organization[] = [
  {
    id: 1,
    name: 'The DEA',
    long: 60,
    lat: 61,
    createdAt: new Date('2020-11-18T05:10:26.416Z'),
    updatedAt: new Date('2020-11-18T05:10:26.416Z'),
    applicationStatus: 'draft',
    active: false,
    contactName: 'Sonja Johanson',
    contactEmail: 'skylerwhite@gmail.com',
    organizationType: null,
    workType: null,
    address: '120 Sproul Hall',
    missionStatement: null,
    shortHistory: null,
    keyValue: null,
    lgbtqDemographic: ['lgbtqAll', 'sgl'],
    raceDemographic: ['asian', 'black'],
    ageDemographic: ['teen', 'adult'],
    capacity: null,
    ein: null,
    foundingDate: null,
    is501c3: false,
    userId: null,
  },
  {
    id: 2,
    name: 'NBJC',
    long: 60,
    lat: 61,
    createdAt: new Date('2020-11-18T05:10:26.416Z'),
    updatedAt: new Date('2020-11-18T05:10:26.416Z'),
    applicationStatus: 'draft',
    active: false,
    contactName: 'Sonja Johanson',
    contactEmail: 'skylerwhite@gmail.com',
    organizationType: null,
    workType: null,
    address: '120 Sproul Hall',
    missionStatement: null,
    shortHistory: null,
    keyValue: null,
    lgbtqDemographic: ['lgbtqAll', 'sgl'],
    raceDemographic: ['asian', 'black'],
    ageDemographic: ['teen', 'adult'],
    capacity: null,
    ein: null,
    foundingDate: null,
    is501c3: false,
    userId: null,
  },
  {
    id: 3,
    name: 'Blueprint',
    long: 60,
    lat: 61,
    createdAt: new Date('2020-11-18T05:10:26.416Z'),
    updatedAt: new Date('2020-11-18T05:10:26.416Z'),
    applicationStatus: 'draft',
    active: false,
    contactName: 'Sonja Johanson',
    contactEmail: 'skylerwhite@gmail.com',
    organizationType: null,
    workType: null,
    address: '120 Sproul Hall',
    missionStatement: null,
    shortHistory: null,
    keyValue: null,
    lgbtqDemographic: ['lgbtqAll', 'sgl'],
    raceDemographic: ['asian', 'black'],
    ageDemographic: ['teen', 'adult'],
    capacity: null,
    ein: null,
    foundingDate: null,
    is501c3: false,
    userId: null,
  },
  {
    id: 4,
    name: 'LGBTQ Task Force',
    long: 60,
    lat: 61,
    createdAt: new Date('2020-11-18T05:10:26.416Z'),
    updatedAt: new Date('2020-11-18T05:10:26.416Z'),
    applicationStatus: 'draft',
    active: false,
    contactName: 'Sonja Johanson',
    contactEmail: 'skylerwhite@gmail.com',
    organizationType: null,
    workType: null,
    address: '120 Sproul Hall',
    missionStatement: null,
    shortHistory: null,
    keyValue: null,
    lgbtqDemographic: ['lgbtqAll', 'sgl'],
    raceDemographic: ['asian', 'black'],
    ageDemographic: ['teen', 'adult'],
    capacity: null,
    ein: null,
    foundingDate: null,
    is501c3: false,
    userId: null,
  },
];

export const sampleQuestionData: Question[] = [
  { id: 1, content: 'asdfsdfdfasdf' },
  { id: 2, content: 'testing' },
  { id: 3, content: 'helloheloooeoeoeoe' },
  { id: 4, content: 'Yellowprint!!!!' },
];
